version: "3.8"

services:
  rabbit:
    image: rabbitmq:3.13-management
    container_name: rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    command: >
      bash -lc "
      rabbitmq-plugins enable --offline rabbitmq_management rabbitmq_delayed_message_exchange &&
      rabbitmq-server
      "
